"""empty message

Revision ID: 07b51c401d32
Revises: 1381eeb75ee1
Create Date: 2017-10-23 06:57:51.928981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07b51c401d32'
down_revision = '1381eeb75ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('authors', 'is_disable')
    op.add_column('editors', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('editors', 'is_active')
    op.add_column('authors', sa.Column('is_disable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('authors', 'is_active')
    # ### end Alembic commands ###
