"""empty message

Revision ID: 08df1431d7d7
Revises: 821bd80e3113
Create Date: 2017-10-24 06:42:16.474394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08df1431d7d7'
down_revision = '821bd80e3113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'published_dates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published_dates', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('posts', 'published_date')
    # ### end Alembic commands ###
