"""empty message

Revision ID: 1d6ebabf0878
Revises: 3bfb42aa9faa
Create Date: 2017-10-04 12:10:08.784215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6ebabf0878'
down_revision = '3bfb42aa9faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('media', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'users', ['user_id'], ['id'])
    op.add_column('tags', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'user_id')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'user_id')
    op.drop_table('editors')
    # ### end Alembic commands ###
