"""empty message

Revision ID: 3bfb42aa9faa
Revises: b1bd19148b43
Create Date: 2017-10-04 11:59:46.392843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfb42aa9faa'
down_revision = 'b1bd19148b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('feature_image', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'media', ['feature_image'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'feature_image')
    # ### end Alembic commands ###
