"""empty message

Revision ID: 589b17807059
Revises: d1c1dc96dce9
Create Date: 2017-10-06 11:10:58.194578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '589b17807059'
down_revision = 'd1c1dc96dce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('access_tokens', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.drop_column('access_tokens', 'created_time')
    op.add_column('authors', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('authors', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('drafts', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('drafts', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('drafts', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('drafts_ibfk_1', 'drafts', type_='foreignkey')
    op.create_foreign_key(None, 'drafts', 'posts', ['post_id'], ['id'])
    op.add_column('editors', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('editors', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('media', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('media', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'updated_on')
    op.drop_column('posts', 'created_on')
    op.add_column('tags', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('tags', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_modified')
    op.drop_column('users', 'date_created')
    op.drop_column('tags', 'date_modified')
    op.drop_column('tags', 'date_created')
    op.add_column('posts', sa.Column('created_on', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('updated_on', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('posts', 'date_modified')
    op.drop_column('posts', 'date_created')
    op.drop_column('media', 'date_modified')
    op.drop_column('media', 'date_created')
    op.drop_column('editors', 'date_modified')
    op.drop_column('editors', 'date_created')
    op.drop_constraint(None, 'drafts', type_='foreignkey')
    op.create_foreign_key('drafts_ibfk_1', 'drafts', 'posts', ['id'], ['id'])
    op.drop_column('drafts', 'post_id')
    op.drop_column('drafts', 'date_modified')
    op.drop_column('drafts', 'date_created')
    op.drop_column('authors', 'date_modified')
    op.drop_column('authors', 'date_created')
    op.add_column('access_tokens', sa.Column('created_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('access_tokens', 'date_modified')
    op.drop_column('access_tokens', 'date_created')
    # ### end Alembic commands ###
