"""empty message

Revision ID: 6580feab3bdc
Revises: d4dc3145eb0e
Create Date: 2017-10-05 16:39:30.006069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6580feab3bdc'
down_revision = 'd4dc3145eb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'access_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_tokens', type_='foreignkey')
    # ### end Alembic commands ###
