"""empty message

Revision ID: 7572186d74c1
Revises: a836709b9343
Create Date: 2017-10-18 11:07:11.188359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7572186d74c1'
down_revision = 'a836709b9343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('label', table_name='tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('label', 'tags', ['label'], unique=True)
    # ### end Alembic commands ###
