"""empty message

Revision ID: 821bd80e3113
Revises: 07b51c401d32
Create Date: 2017-10-24 06:24:00.773559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '821bd80e3113'
down_revision = '07b51c401d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published_dates', sa.Integer(), nullable=True))
    op.drop_column('posts', 'published_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published_date', mysql.DATETIME(), nullable=True))
    op.drop_column('posts', 'published_dates')
    # ### end Alembic commands ###
