"""empty message

Revision ID: 979f10a33d57
Revises: 6580feab3bdc
Create Date: 2017-10-05 16:40:17.849238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979f10a33d57'
down_revision = '6580feab3bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_tokens', sa.Column('demo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_tokens', 'demo')
    # ### end Alembic commands ###
