"""empty message

Revision ID: aea2b0136c97
Revises: ba7814a36fbf
Create Date: 2017-10-10 12:01:52.432928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea2b0136c97'
down_revision = 'ba7814a36fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'is_active')
    # ### end Alembic commands ###
