"""empty message

Revision ID: ba7814a36fbf
Revises: 589b17807059
Create Date: 2017-10-06 14:13:44.739903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7814a36fbf'
down_revision = '589b17807059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'is_disable')
    # ### end Alembic commands ###
