"""empty message

Revision ID: d0961866e61a
Revises: fa30896e43b8
Create Date: 2017-10-04 11:47:08.203589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0961866e61a'
down_revision = 'fa30896e43b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('tag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'tag_id')
    op.drop_column('posts', 'author_id')
    op.drop_table('authors')
    # ### end Alembic commands ###
