"""empty message

Revision ID: d1c1dc96dce9
Revises: c4115f603108
Create Date: 2017-10-06 10:38:19.788900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c1dc96dce9'
down_revision = 'c4115f603108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('authors_ibfk_1', 'authors', type_='foreignkey')
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.create_foreign_key('authors_ibfk_1', 'authors', 'users', ['id'], ['id'])
    op.drop_column('authors', 'user_id')
    # ### end Alembic commands ###
