"""empty message

Revision ID: d4dc3145eb0e
Revises: 1d6ebabf0878
Create Date: 2017-10-04 13:03:00.566589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dc3145eb0e'
down_revision = '1d6ebabf0878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_on', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'created_on')
    # ### end Alembic commands ###
