"""empty message

Revision ID: d836b35241b7
Revises: aea2b0136c97
Create Date: 2017-10-18 07:32:18.198876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd836b35241b7'
down_revision = 'aea2b0136c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'is_active')
    # ### end Alembic commands ###
