"""empty message

Revision ID: e64947a619ce
Revises: aea2b0136c97
Create Date: 2017-10-18 10:47:13.576036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e64947a619ce'
down_revision = 'aea2b0136c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('media_ibfk_1', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'authors', ['author_id'], ['id'])
    op.drop_column('media', 'user_id')
    op.add_column('tags', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('tags_ibfk_1', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'authors', ['author_id'], ['id'])
    op.drop_column('tags', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_ibfk_1', 'tags', 'users', ['user_id'], ['id'])
    op.drop_column('tags', 'author_id')
    op.add_column('media', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_ibfk_1', 'media', 'users', ['user_id'], ['id'])
    op.drop_column('media', 'author_id')
    # ### end Alembic commands ###
