"""empty message

Revision ID: fa30896e43b8
Revises: 02de8d3071f3
Create Date: 2017-10-04 10:42:59.575692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa30896e43b8'
down_revision = '02de8d3071f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('is_private', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_draft', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('published_date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('updated_on', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('body', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('likes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
